name: Build BoomingMusic APK (from uploaded zip)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
name: Build APK from BoomingMusic Zip

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip BoomingMusic-1.1.0-beta.8.zip
        run: unzip BoomingMusic-1.1.0-beta.8.zip -d src

      - name: List files for debugging
        run: ls -R src

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build APK
        run: |
          cd src/BoomingMusic-1.1.0-beta.8
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BoomingMusic-APK
          path: src/BoomingMusic-1.1.0-beta.8/app/build/outputs/apk/deb
          ug/*.apkact@v4
        with:
          name: BoomingMusic-debug
          path: app/build/outputs/apk/
          **/*.apk
